# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Escuela de Enseñanza Secundaria Orientada n° 521
email: eeso521lopez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  La Escuela de Enseñanza Secundaria Orientada N° 521 es la única escuela secundaria de la localidad de López, en la provincia de Santa Fé.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eeso521.tk" # the base hostname & protocol for your site
facebook_username: jekyllrb

# Build settings
markdown: kramdown
